from django.urls import path
from .views import (
    PortfolioDashboardView, 
    AddTransactionView, 
    CSVImportView, 
    UpdatePricesView,
    CashFlowListCreateView,
    CashFlowDetailView,
    AccountBalanceView,
    RecalculateBalanceView,
    TransactionListView,
    TransactionDetailView,
    ValidateSymbolView,
    SearchStocksView,
    StockListCacheView,
    PortfolioHistoryView,
    StockHistoryView,
    MonthlyTrackingView,
    MonthlyTrackingYearsView,
    DailySnapshotView,
    DailySnapshotHistoryView
)

urlpatterns = [
    path('dashboard/', PortfolioDashboardView.as_view(), name='dashboard'),
    path('add-transaction/', AddTransactionView.as_view(), name='add-transaction'),
    path('transactions/', TransactionListView.as_view(), name='transaction-list'),
    path('transactions/<int:pk>/', TransactionDetailView.as_view(), name='transaction-detail'),
    path('import-csv/', CSVImportView.as_view(), name='import-csv'),
    path('update-prices/', UpdatePricesView.as_view(), name='update-prices'),
    path('cashflow/', CashFlowListCreateView.as_view(), name='cashflow-list-create'),
    path('cashflow/<int:pk>/', CashFlowDetailView.as_view(), name='cashflow-detail'),
    path('account-balance/', AccountBalanceView.as_view(), name='account-balance'),
    path('recalculate-balance/', RecalculateBalanceView.as_view(), name='recalculate-balance'),
    path('validate-symbol/', ValidateSymbolView.as_view(), name='validate-symbol'),
    path('search-stocks/', SearchStocksView.as_view(), name='search-stocks'),
    path('stock-list-cache/', StockListCacheView.as_view(), name='stock-list-cache'),
    path('portfolio-history/', PortfolioHistoryView.as_view(), name='portfolio-history'),
    path('stock-history/', StockHistoryView.as_view(), name='stock-history'),
    path('monthly-tracking/', MonthlyTrackingView.as_view(), name='monthly-tracking'),
    path('monthly-tracking-years/', MonthlyTrackingYearsView.as_view(), name='monthly-tracking-years'),
    path('daily-snapshot/', DailySnapshotView.as_view(), name='daily-snapshot'),
    path('daily-snapshot/history/', DailySnapshotHistoryView.as_view(), name='daily-snapshot-history'),
]