# Generated by Django 6.0.1 on 2026-01-19 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='股票代號 (e.g. AAPL)', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='公司名稱', max_length=100)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD')], default='USD', max_length=3)),
                ('sector', models.CharField(blank=True, help_text='板塊 (e.g. Tech)', max_length=50)),
                ('current_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('last_price_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy (買入)'), ('SELL', 'Sell (賣出)'), ('DIVIDEND', 'Dividend (股息)'), ('DEPOSIT', 'Deposit (入金)'), ('WITHDRAW', 'Withdraw (出金)')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, help_text='成交單價', max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='股數 (賣出為負數?) - 建議這裡存絕對值，邏輯由 action 判斷', max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, help_text='手續費', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.asset')),
            ],
        ),
    ]
