# Generated by Django 6.0.1 on 2026-01-19 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_cash', models.DecimalField(decimal_places=2, default=0.0, help_text='目前可用現金', max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balance',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='金額', max_digits=15)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit (存入)'), ('WITHDRAW', 'Withdraw (提取)')], help_text='類型：存入或提取', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='日期')),
                ('notes', models.TextField(blank=True, help_text='備註', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'verbose_name_plural': 'Cash Flows',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
