# Generated by Django 5.2.10 on 2026-01-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_cleanup_old_data_and_make_user_required'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashflow',
            new_name='portfolio_c_user_id_aeab06_idx',
            old_name='portfolio_c_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='portfolio_t_user_id_6c271c_idx',
            old_name='portfolio_t_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='portfolio_t_user_id_306b39_idx',
            old_name='portfolio_t_user_id_asset_idx',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD')], default='USD', help_text='現金流幣種', max_length=3),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='交易時的匯率（相對於基準幣種）', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD')], default='USD', help_text='交易幣種', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='交易時的匯率（相對於基準幣種）', max_digits=10, null=True),
        ),
    ]
