# Generated by Django 5.2.10 on 2026-01-29 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_update_accountbalance_for_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='available_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='目前可用現金（已棄用，使用 total_in_base）', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy (買入)'), ('SELL', 'Sell (賣出)'), ('DIVIDEND', 'Dividend (股息)')], max_length=10),
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='快照日期')),
                ('net_liquidity', models.DecimalField(decimal_places=2, help_text='淨資產（總市值 + 總現金）', max_digits=15)),
                ('current_cash', models.DecimalField(decimal_places=2, help_text='可用現金（USD 基準）', max_digits=15)),
                ('cash_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='USD 現金餘額', max_digits=15)),
                ('cash_hkd', models.DecimalField(decimal_places=2, default=0.0, help_text='HKD 現金餘額', max_digits=15)),
                ('total_market_value', models.DecimalField(decimal_places=2, help_text='總持倉市值', max_digits=15)),
                ('total_invested', models.DecimalField(decimal_places=2, help_text='總投入本金', max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, help_text='淨利潤', max_digits=15)),
                ('roi_percentage', models.DecimalField(decimal_places=2, help_text='總回報率 (%)', max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='USD/HKD 匯率', max_digits=10)),
                ('positions', models.JSONField(default=dict, help_text='各持倉快照 { symbol: { quantity, current_market_value, avg_cost, ... } }')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='擁有此快照的用戶', on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Snapshot',
                'verbose_name_plural': 'Daily Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='portfolio_d_user_id_0e2a6a_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
